# Generated by Django 5.0.3 on 2024-05-09 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cpation',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 15, 0, 45, 944158)),
        ),
    ]
