# Generated by Django 5.0.3 on 2024-05-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_followerscount_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 12, 27, 13, 459464)),
        ),
    ]
